notifications:
  email: false
env:
  - CABALVER=1.24
language: haskell
ghc: 8.0
install:
  - sudo apt-get install -y libsdl2-dev
  - cabal install --only-dependencies --enable-tests
script:
  - cabal configure --enable-tests
  - cabal build
  - cabal test
