notifications:
  email: false
env:
  - CABALVER=1.22
language: haskell
ghc: 7.8
install:
  - cabal install --only-dependencies --enable-tests --reorder-goals
  - cabal install happy
  - cabal install hlint
script:
  - cabal configure --enable-tests
  - cabal build
  - cabal test
  - hlint .
