notifications:
  email: false
sudo: required
language: generic
dist: trusty
addons:
  apt:
    packages:
      - libsdl2-dev
before_install:
  # Download and install Haskell Stack
  - mkdir -p ~/.stack-home
  - export PATH=$HOME/.stack-home:$PATH
  - travis_retry wget https://www.stackage.org/stack/linux-x86_64 -O stack.tar
  - tar xz -f stack.tar --wildcards --strip-components=1 -C ~/.stack-home '*/stack'
install:
#  - stack --no-terminal --install-ghc test --only-dependencies
   - true
script:
#  - stack --no-terminal test --haddock --no-haddock-deps
   - true
