notifications:
  email: false
env:
  - CABALVER=1.24
language: haskell
ghc: 8.0
install:
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu trusty universe"
  - sudo apt-get -qq update
  - sudo apt-get -y install libsdl2-2.0-0
  - cabal install --only-dependencies --enable-tests
script:
  - cabal configure --enable-tests
  - cabal build
  - cabal test
